### ISSUE TITLE
Notification about submissions

### ISSUE THREAD

**Issue by moniquewiza** [EUSurvey/EUSURVEY#243]
Current version does not permit a survey owner to be notified about new submissions. In some cases it is important - we have surveys that lasts whole year or longer. It would be good that a survey owner does not have to check survey every few days, but is notified about comming subscriptions.

In survey properites it could be an option 'notify owner about submissions' where notification would be sent to the email specified in 'Contact'.

**Comment by catalry** [comment]
Dear @wojciechwiza, we are actually working on a solution which is almost what you are suggesting.
Here is an overview:
Create and send per email automatic "survey reports" including:
- the total number of contributions (against target, i.e. maximum number of contributions)
- the number of new contributions since the last report
- the number of new contributions made ; minus
- the number of contributions withdrawn

Also, we would let Form Manager decide to be informed never (default) / weekly / monthly. However, we would send the report per email to the FM's email address.

**Comment by moniquewiza** [comment]
@catalry Thanks for the info. It would be great to have it. May I suggest to add also daily notification?
I thouhgt about contact email cause this is typically related to some functional mailbox, but form manager is indeed good solution.

**Comment by catalry** [comment]
Sure, we will take this into account. Thank you for your suggestion!
If this is all I will close this issue?

**Comment by moniquewiza** [comment]
Yes. Please check my two other posted issues.

**Comment by Kath-estrd** [comment]
> Current version does not permit a survey owner to be notified about new submissions. In some cases it is important - we have surveys that lasts whole year or longer. It would be good that a survey owner does not have to check survey every few days, but is notified about comming subscriptions.
> 
> In survey properites it could be an option 'notify owner about submissions' where notification would be sent to the email specified in 'Contact'.
